bag/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.view_bag, name='bag'),
    path('add/<pack_id>', views.add_to_bag, name='add_to_bag'),
    path('remove_from_bag/<pack_id>/', views.remove_from_bag,
         name='remove_from_bag'),
]

grizzly_audio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('packs/', include('packs.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

packs/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.all_packs, name='packs'),
    path('add/', views.add_pack, name='add_pack'),
    path('edit/<int:pack_id>/', views.edit_pack, name='edit_pack'),
    path('delete/<int:pack_id>', views.delete_pack, name='delete_pack'),
]

packs/models.py
from django.db import models


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=False,
                                     blank=False, default=name)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Pack(models.Model):
    sku = models.CharField(max_length=254, null=False, blank=False)
    name = models.CharField(max_length=254)
    description = models.TextField()
    publish_date = models.DateField(auto_now_add=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    on_sale = models.BooleanField(default=False)
    reduced_price = models.DecimalField(max_digits=6, decimal_places=2,
                                        null=True, blank=True)
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    sales = models.IntegerField(null=False, blank=False, default='0',
                                editable=False)
    image = models.ImageField(null=False, blank=True)
    sample_track = models.FileField(null=False, blank=True)
    download_file = models.FileField(null=False, blank=False, default='.')

    def __str__(self):
        return self.name

packs/forms.py
from django import forms
from .widgets import CustomClearableFileInput, CustomClearableImageInput
from .models import Pack, Category


class PackForm(forms.ModelForm):
    class Meta:
        model = Pack
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False,
                             widget=CustomClearableImageInput)
    sample_track = forms.FileField(label='Sample Track', required=False,
                                   widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        # Adds placeholders and classes to form fields,
        # removes auto-generated labels and sets auto-focus
        # on the first field of the page
        super().__init__(*args, **kwargs)
        placeholders = {
            'name': 'Pack Name',
            'sku': 'SKU Number',
            'description': 'Description',
            'category': 'Category',
            'price': 'Price',
            'on_sale': 'On Sale?',
            'reduced_price': 'Reduced Price',
            'image': 'Image',
            'sample_track': 'Sample Track',
            'download_file': 'Download File',
        }
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]
        self.fields['category'].choices = friendly_names
        self.fields['description'].widget.attrs['rows'] = '5'
        for field in self.fields:
            if self.fields[field].required:
                placeholder = f'{placeholders[field]} *'
            else:
                placeholder = placeholders[field]
            self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'stripe-style-input'
            if field != 'on_sale':
                self.fields[field].widget.attrs['class'] = \
                    'stripe-style-input w-100'
            self.fields[field].label = False

packs/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Pack, Category
from .forms import PackForm


def all_packs(request):
    # Show all audio packs, allow sorting and search queries

    packs = Pack.objects.all()
    query = None
    sort = None
    direction = None
    categories = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                packs = packs.annotate(lower_name=Lower('name'))
                messages.info(request, 'Sorting by: Name')
            if sortkey == 'date':
                sortkey = 'publish_date'
                messages.info(request, 'Sorting by: Publication Date')
            if sortkey == 'category':
                sortkey = 'category__name'
                messages.info(request, 'Sorting by: Category')
            if sortkey == 'price':
                sortkey = 'price'
                messages.info(request, 'Sorting by: Price')
            if sortkey == 'freepacks':
                sortkey = 'lower_name'
                packs = packs.filter(price=0.00)
                packs = packs.annotate(lower_name=Lower('name'))
                messages.info(request, 'Sorting by: Free Packs')
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            else:
                direction = 'desc'
            packs = packs.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            packs = packs.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)
            for term in categories:
                category_term = term.friendly_name
            messages.info(request, f'You are searching for: {category_term}')

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.warning(request, "You did not enter any search\
                    criteria")
                return redirect(reverse('packs'))

            queries = Q(name__icontains=query) |\
                Q(description__icontains=query)
            messages.info(request, f'You are searching for: "{query}"')
            packs = packs.filter(queries)
    edit_pack_form = PackForm()
    context = {
        'packs': packs,
        'search_term': query,
        'current_sorting': sort,
        'current_direction': direction,
        'current_categories': categories,
        'edit_pack_form': edit_pack_form,
    }

    return render(request, 'packs/packs.html', context)


@login_required
def add_pack(request):
    # Allows store owners to add a pack to the store
    # Check if user is a store owner
    if not request.user.is_superuser:
        messages.error(request, 'You do not have access to this page.')
        return redirect(reverse('home'))
    if request.method == 'POST':
        form = PackForm(request.POST, request.FILES)
        if form.is_valid():
            pack = form.save()
            messages.success(request, f'Successfully added new pack: \
                {pack.name}!')
            if 'id_saveandview' in request.POST:
                return redirect(reverse('packs'))
            else:
                return redirect(reverse('add_pack'))
        else:
            print(form.errors)
            messages.error(request, 'Failed to add pack. Please confirm\
            the information you entered, and try again.')
    else:
        form = PackForm()
    template = 'packs/add_pack.html'
    all_cat = Category.objects.all()
    context = {
        'form': form,
        'categories': all_cat,
    }
    return render(request, template, context)


@login_required
def edit_pack(request, pack_id):
    # Allow store owners to edit an existing pack
    # Check if user is a store owner
    if not request.user.is_superuser:
        messages.error(request, 'You do not have access to this page.')
        return redirect(reverse('home'))
    pack = get_object_or_404(Pack, pk=pack_id)
    if request.method == 'POST':
        form = PackForm(request.POST, request.FILES, instance=pack)
        if form.is_valid():
            form.save()
            messages.success(request, f'Successfully updated pack: \
                {pack.name}!')
            return redirect(reverse('packs'))
        else:
            print(form.errors)
            messages.error(request, 'Failed to update pack. Please confirm\
            the information you entered, and try again.')
    else:
        form = PackForm(instance=pack)
        messages.info(request, f'You are editing {pack.name}')
    template = 'packs/edit_pack.html'
    all_cat = Category.objects.all()
    context = {
        'form': form,
        'pack': pack,
        'categories': all_cat,
    }
    return render(request, template, context)


@login_required
def delete_pack(request, pack_id):
    # Allows store owners to delete an existing product
    # Check if user is a store owner
    if not request.user.is_superuser:
        messages.error(request, 'You do not have access to this page.')
        return redirect(reverse('home'))
    pack = get_object_or_404(Pack, pk=pack_id)
    pack.delete()
    messages.success(request, 'Pack has been successfully deleted!')
    return redirect(reverse('packs'))

packs/templates/packs/add_pack.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/form-style.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid margin-tb-75">
        <div class="row">
            <div class="col-10 offset-1">
                <h2 class="text-uppercase mt-4 text-center font-weight-light header-spacing">Add A New Pack</h2>
            </div>
            <hr class="w-100 mb-1">
        </div>
        <div class="row mt-3">
            <div class="col-10 offset-1">
                <form method="POST" action="{% url 'add_pack'%}" class="form mb-2" enctype="multipart/form-data" id="add_pack_form">
                    {% csrf_token %}
                        <div class="row">
                            <div class="col-12 col-sm-6">
                                {{ form.name }}
                                {{ form.sku }}
                                {{ form.description }}
                                <div class="row">
                                    <div class="col-3">
                                        <label for="id_category" class="text-uppercase font-weight-light" style="line-height: 40px;">Category:</label>
                                    </div>
                                    <div class="col-9">
                                        {{ form.category }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        {{ form.price }}
                                        {{ form.on_sale }}
                                        <label for="id_on_sale" class="text-uppercase font-weight-light">On Sale?</label>
                                    </div>
                                    <div class="col-6">
                                        {{ form.reduced_price }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="row">
                                    <div class="col-12">
                                    <label for="id_image" class="text-uppercase font-weight-light w-25">Select Image:</label>
                                    {{ form.image }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                    <label for="id_sample_track" class="text-uppercase font-weight-light w-25">Sample Track:</label>
                                    {{ form.sample_track }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    <div class="float-right">
                        <button type="submit" name="id_addanother" class="btn btn-darkgrey rounded-0 mt-5 save-btn">
                            <i class="fas fa-plus-circle d-none"></i>
                            <p class="text-uppercase font-weight-light mb-0">Add Another</p>
                        </button>
                        <button type="submit" name="id_saveandview" class="btn btn-darkgrey rounded-0 mt-5 save-btn">
                            <i class="far fa-check-circle d-none"></i>
                            <p class="text-uppercase font-weight-light mb-0">Save And View</p>
                        </button>
                        <a href="{% url 'packs' %}" class="btn btn-darkgrey rounded-0 mt-5 cancel-btn">
                            <i class="fas fa-trash d-none">
                            </i>
                            <p class="text-uppercase font-weight-light mb-0">Cancel Changes</p>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/add-edit-pack.js' %}"></script>
{% endblock %}

packs/templates/packs/edit_pack.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/form-style.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid margin-tb-75">
        <div class="row">
            <div class="col-10 offset-1">
                <h2 class="text-uppercase mt-4 text-center font-weight-light header-spacing">Edit A Pack</h2>
            </div>
            <hr class="w-100 mb-1">
        </div>
        <div class="row mt-3">
            <div class="col-10 offset-1">
                <form method="POST" action="{% url 'edit_pack' pack.id %}" class="form mb-2" enctype="multipart/form-data" id="edit_pack_form">
                    {% csrf_token %}
                        <div class="row">
                            <div class="col-12 col-sm-6">
                                {{ form.name }}
                                {{ form.sku }}
                                {{ form.description }}
                                <div class="row">
                                    <div class="col-3">
                                        <label for="id_category" class="text-uppercase font-weight-light" style="line-height: 40px;">Category:</label>
                                    </div>
                                    <div class="col-9">
                                        {{ form.category }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        {{ form.price }}
                                        {{ form.on_sale }}
                                        <label for="id_on_sale" class="text-uppercase font-weight-light">On Sale?</label>
                                    </div>
                                    <div class="col-6">
                                        {{ form.reduced_price }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="row">
                                    <div class="col-12">
                                    <label for="id_image" class="text-uppercase font-weight-light w-25">Select Image:</label>
                                    {{ form.image }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                    <label for="id_sample_track" class="text-uppercase font-weight-light w-25">Sample Track:</label>
                                    {{ form.sample_track }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    <div class="float-right">
                        <button class="btn btn-darkgrey rounded-0  mt-5 save-btn">
                            <i class="fas fa-check d-none"></i>
                            <p class="d-block mb-0 underline-hover text-uppercase font-weight-light">Save Changes</p>
                        </button>
                        <a href="{% url 'packs' %}" class="btn btn-darkgrey rounded-0 mt-5 cancel-btn">
                            <i class="fas fa-trash d-none">
                            </i>
                            <p class="mb-0 d-block underline-hover text-uppercase font-weight-light">Cancel Changes</p>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/add-edit-pack.js' %}">
    </script>
{% endblock %}

packs/templates/packs/packs.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/packs/modal-styles.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid margin-tb-75">
        <div class="row">
            <div class="col-10 offset-1 text-center">
                <h2 class="text-uppercase mt-5 font-weight-light header-spacing">All {% for cat in current_categories %}{{ cat.friendly_name }}{% endfor %} Packs</h2>
            </div>
            <div class="col-1">
                {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser %}
                            <a href="{% url 'add_pack' %}" id="add-pack-btn" type="button" class="btn btn-darkgrey rounded-0 text-uppercase float-right d-inline-block mt-4" data-toggle="tooltip" data-placement="left" title="Add A New Pack">
                                <i class="far fa-lg fa-plus-square"></i>
                            </a>
                    {% endif %}
                {% endif %}
            </div>
            <hr class="w-100 mb-1">
        </div>
        
        <div class="row text-uppercase">
            <div class="col-10 col-lg-5 offset-1 pl-5 pr-0">
                <button id="changedirection" class="border-0 bg-white">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrows-sort" width="24" height="24" viewbox="0 0 24 24" stroke-width="1.0" stroke="#292929" fill="none" stroke-linecap="round" stroke-linejoin="round" >
                    <path stroke="none" d="M0 0h24v24H0z"/>
                    <path d="M3 9l4-4l4 4m-4 -4v14" />
                    <path d="M21 15l-4 4l-4-4m4 4v-14" />
                    </svg>
                </button>
                <p id="pack-count" class="font-weight-light d-inline-block">{{ packs|length }} pack(s)
                {% if search_term %}
                    with search term: <strong>"{{ search_term }}" </strong><a href="{% url 'packs' %}{% if current_sorting %}?sort={{ current_sorting }}{% endif %}{% if current_direction %}&direction={{ current_direction }}{% endif %}" class="text-black"> <i class="far fa-times-circle"></i></a>
                {% endif %}
                {% if current_categories %}
                    with category: <strong>{% for cat in current_categories %}"{{ cat.friendly_name }}"{% endfor %}</strong><a href="{% url 'packs' %}{% if current_sorting %}?sort={{ current_sorting }}{% endif %}{% if current_direction %}&direction={{ current_direction }}{% endif %}" class="text-black"> <i class="far fa-times-circle"></i></a>
                {% endif %}
                {% if current_sorting %}
                    sorted by: <strong>"{{ current_sorting }}"</strong> <a href="{% url 'packs' %}" class="text-black"> <i class="far fa-times-circle"></i></a>
                {% endif %}
                </p>
            </div>
            <div class="col-10 offset-1 col-lg-5 offset-lg-0 text-right px-5">
                <select name="sortby" id="sortbyoptions" class="font-weight-light text-uppercase">
                    <option value="-">Sort By</option>
                    <option {% if current_sorting == 'name' %}selected{% endif %} value="name">Name {% if current_sorting == 'name' and current_direction == 'asc' %}(A-Z){% else %}(Z-A){% endif %}</option>
                    <option {% if current_sorting == 'freepacks' %}selected{% endif %} value="freepacks">Free Packs</option>
                    <option {% if current_sorting == 'date' %}selected{% endif %} value="date">Publication Date {% if current_sorting == 'date' %}({{ current_direction }}){% endif %}</option>
                    <option {% if current_sorting == 'sales' %}selected{% endif %} value="sales">Popularity {% if current_sorting == 'sales' %}({{ current_direction }}){% endif %}</option>
                    <option {% if current_sorting == 'price' %}selected{% endif %} value="price">Price {% if current_sorting == 'price' %}({{ current_direction }}){% endif %}</option>
                    <option {% if current_sorting == 'category' %}selected{% endif %} value="category">Category {% if current_sorting == 'category' %}({{ current_direction }}){% endif %}</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-10 offset-1">
                <div class="row">
                    {% for pack in packs %}
                        <div class="col-sm-6 col-lg-4 col-xl-3">
                            <div class="pack-card card h-100 border-0 mx-auto my-4">
                                {% if pack.image %}
                                <div class="img-container pack-display">
                                    {% if pack.on_sale %}
                                    <span class="badge badge-danger">On Sale!</span>
                                    {% endif %}
                                    <a href="" class="h-100" data-toggle="modal" data-target="#pack{{ pack.id }}Modal">
                                        <img src="{{ pack.image.url }}" alt="{{ pack.name }}" class="card-img-top img-fluid">
                                    </a>
                                    
                                </div>
                                {% else %}
                                <div class="img-container">
                                    <a href="" class="h-100" data-toggle="modal" data-target="#pack{{ pack.id }}Modal">
                                        <img src="{{ MEDIA_URL }}noimage.png" alt="{{ pack.name }}" class="card-img-top img-fluid">
                                    </a>
                                </div>
                                {% endif %}
                                <div class="card-body p-2 pb-0">
                                    <a href="" class="mb-0 text-black font-weight-light text-uppercase" data-toggle="modal" data-target="#pack{{ pack.id }}Modal">{{ pack.name|truncatechars:20 }}</a>
                                    <br>
                                    <a href="{% url 'packs' %}?category={{ pack.category.name }}" class="mb-0 text-black text-uppercase"><small>{{ pack.category.friendly_name }}</small></a>
                                    <br>
                                    <small>{% if pack.on_sale %}<s class="text-muted">£{{ pack.price }}</s> {{ pack.reduced_price }}{% else %} £{{ pack.price }}{% endif %}</small>
                                    {% if request.user.is_authenticated %}
                                        {% if request.user.is_superuser %}
                                            <br>
                                            <a href="{% url 'edit_pack' pack.id %}" class="mb-0 text-info"><small>Edit</small></a>
                                            <a href="" class="mb-0 ml-2 text-danger" data-toggle="modal" data-target="#confirm-delete-{{ pack.id }}-modal"><small>Remove</small></a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <!-- Using Bootstrap Modal Components -->
                        <!-- https://getbootstrap.com/docs/4.0/components/modal/ -->
                        {% include 'packs/packmodals/pack_detail.html' %}
                        <!-- Great bit of code found at https://github.com/ckz8780/boutique_ado_v1/blob/f5880efee43b3b9ea1276a09ca972f4588001c59/products/templates/products/products.html -->
                        <!-- Creates a <hr> depending on the window width -->
                        {% if forloop.counter|divisibleby:1 %}
                            <div class="col-12 d-sm-none mb-5">
                                <hr class="invisible">
                            </div>
                        {% endif %}                        
                        {% if forloop.counter|divisibleby:2 %}
                            <div class="col-12 d-none d-sm-block d-md-block d-lg-none mb-5">
                                <hr class="invisible">
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:3 %}
                            <div class="col-12 d-none d-lg-block d-xl-none mb-5">
                                <hr class="invisible">
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:4 %}
                            <div class="col-12 d-none d-xl-block mb-5">
                                <hr class="invisible">
                            </div>
                        {% endif %}    
                    {% endfor %}
                    {% if current_categories or search_term or current_sorting == 'freepacks' %}
                        <div class="col-sm-6 col-lg-4 col-xl-3">
                            <div class="pack-card card h-100 border-0 mx-auto my-4">
                                <div class="img-container">
                                    <a href="{% url 'packs' %}">
                                        <img src="https://lindsaykerr1994-grizzlyaudiopacks.s3.amazonaws.com/media/see-all.png" alt="" class="card-img-top img-fluid">
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="btt-button shadow-sm rounded-0 border border-black bg-darkgrey">
        <a class="btt-link d-flex h-100">
            <p class="mb-0 mx-auto font-weight-light text-uppercase text-white">Top</p>
            <i class="fas fa-arrow-up text-black mx-auto my-1 text-white"></i>
        </a>	
    </div>
{% endblock %}

{% block extra_js %}
    {{block.super}}
    <script src="{% static 'js/sortpacks.js' %}"></script>
{% endblock%}